/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: LowPolyBoy (https://sketchfab.com/lowPolyBoy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/character-fight-9ef2f6bd1346475885ce22ea971f8e4e
Title: Character Fight
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Fight(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/character_fight.glb')
  const { actions } = useAnimations(animations, group)
  console.log(animations);

  useEffect(() => {
    actions['Animation']?.play()
  }, [actions])
  
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.203}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Text_0"
                position={[0, 1.544, 0.687]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.322}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group
                name="Text001_1"
                position={[0, 1.544, 0.687]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0}>
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group
                name="Text002_2"
                position={[0, 1.544, 0.687]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={0}>
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group name="Text003_3" position={[0.972, 2.149, 0.687]} scale={0}>
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group name="Text004_4" position={[-1.008, 2.061, 0.687]} scale={0}>
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group name="Text005_5" position={[-0.712, 1.985, 0.687]} scale={0}>
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group name="Text006_6" position={[-0.261, 1.979, 0.687]} scale={0}>
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group name="Text007_7" position={[0.379, 1.985, 0.687]} scale={0}>
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group name="Empty002_8" position={[0, 1.544, 0.687]} />
              <group name="Cube_9" position={[0, -1, 0]}>
                <mesh
                  name="Object_21"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_21.geometry}
                  material={materials.Material}
                />
              </group>
              <group name="Cube001_10" position={[0, -1.513, -0.289]} scale={[0.978, 0.914, 0.978]}>
                <mesh
                  name="Object_23"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_23.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group name="mmt_folia_grass_03_11" position={[0, 0, -1.912]}>
                <mesh
                  name="Object_25"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_25.geometry}
                  material={materials.mmt_foliage}
                />
              </group>
              <group name="mmt_folia_clove_02_12" position={[-2.773, 0, 0.041]}>
                <mesh
                  name="Object_27"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_27.geometry}
                  material={materials.mmt_foliage}
                />
              </group>
              <group name="mmt_folia_clove_02001_13" position={[-0.915, 0, -0.915]}>
                <mesh
                  name="Object_29"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_29.geometry}
                  material={materials.mmt_foliage}
                />
              </group>
              <group name="mmt_folia_clove_02002_14" position={[-2.937, 0, -2.405]}>
                <mesh
                  name="Object_31"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_31.geometry}
                  material={materials.mmt_foliage}
                />
              </group>
              <group name="mmt_folia_clove_02003_15" position={[-0.642, 0, -3.443]}>
                <mesh
                  name="Object_33"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_33.geometry}
                  material={materials.mmt_foliage}
                />
              </group>
              <group name="mmt_folia_clove_02004_16" position={[2.924, 0, -1.967]}>
                <mesh
                  name="Object_35"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_35.geometry}
                  material={materials.mmt_foliage}
                />
              </group>
              <group name="mmt_folia_clove_02005_17" position={[1.148, 0, -2.405]}>
                <mesh
                  name="Object_37"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_37.geometry}
                  material={materials.mmt_foliage}
                />
              </group>
              <group name="mmt_folia_clove_02006_18" position={[0.437, 0, 0.219]}>
                <mesh
                  name="Object_39"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_39.geometry}
                  material={materials.mmt_foliage}
                />
              </group>
              <group name="mmt_folia_clove_02007_19" position={[2.814, 0, 0.123]}>
                <mesh
                  name="Object_41"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_41.geometry}
                  material={materials.mmt_foliage}
                />
              </group>
              <group name="mmt_folia_clove_02008_20" position={[2.418, 0, -3.775]}>
                <mesh
                  name="Object_43"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_43.geometry}
                  material={materials.mmt_foliage}
                />
              </group>
              <group name="mmt_folia_grass_03001_21" position={[1.484, 0, -2.544]}>
                <mesh
                  name="Object_45"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_45.geometry}
                  material={materials.mmt_foliage}
                />
              </group>
              <group name="mmt_folia_grass_03002_22" position={[2.814, 0, -2.391]}>
                <mesh
                  name="Object_47"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_47.geometry}
                  material={materials.mmt_foliage}
                />
              </group>
              <group name="mmt_folia_grass_03003_23" position={[-1.685, 0, -2.821]}>
                <mesh
                  name="Object_49"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_49.geometry}
                  material={materials.mmt_foliage}
                />
              </group>
              <group name="mmt_folia_grass_03004_24" position={[-2.968, 0, -2.199]}>
                <mesh
                  name="Object_51"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_51.geometry}
                  material={materials.mmt_foliage}
                />
              </group>
              <group
                name="mmt_folia_tree_02_25"
                position={[-3.373, 0, -4.599]}
                rotation={[0, 0.546, 0]}
                scale={1.032}>
                <mesh
                  name="Object_53"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_53.geometry}
                  material={materials['mct_atlas.002']}
                />
                <mesh
                  name="Object_54"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_54.geometry}
                  material={materials['mmt_foliage.001']}
                />
              </group>
              <group name="mmt_folia_tree_02001_26" position={[-3.351, 0, -5.983]} scale={1.413}>
                <mesh
                  name="Object_56"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_56.geometry}
                  material={materials['mct_atlas.002']}
                />
                <mesh
                  name="Object_57"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_57.geometry}
                  material={materials['mmt_foliage.001']}
                />
              </group>
              <group
                name="mmt_folia_tree_02002_27"
                position={[-2.256, 0, -3.873]}
                rotation={[0, 0.6, 0]}
                scale={0.666}>
                <mesh
                  name="Object_59"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_59.geometry}
                  material={materials['mct_atlas.002']}
                />
                <mesh
                  name="Object_60"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_60.geometry}
                  material={materials['mmt_foliage.001']}
                />
              </group>
              <group
                name="mmt_build_full_house01_29"
                position={[-0.029, 0, -6.812]}
                rotation={[0, -0.211, 0]}>
                <mesh
                  name="Object_62"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_62.geometry}
                  material={materials['mct_atlas.003']}
                />
                <group name="mmt_build_full_house01_door_28" position={[-1.558, 0.02, 2.146]}>
                  <mesh
                    name="Object_64"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_64.geometry}
                    material={materials['mct_atlas.003']}
                  />
                </group>
              </group>
              <group
                name="mmt_folia_tree_02003_30"
                position={[3.323, 0, -5.69]}
                rotation={[0, 0.546, 0]}
                scale={1.032}>
                <mesh
                  name="Object_66"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_66.geometry}
                  material={materials['mct_atlas.002']}
                />
                <mesh
                  name="Object_67"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_67.geometry}
                  material={materials['mmt_foliage.001']}
                />
              </group>
              <group
                name="mmt_folia_tree_02004_31"
                position={[3.416, 0, -8.221]}
                rotation={[0, 0.546, 0]}
                scale={2.096}>
                <mesh
                  name="Object_69"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_69.geometry}
                  material={materials['mct_atlas.002']}
                />
                <mesh
                  name="Object_70"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={materials['mmt_foliage.001']}
                />
              </group>
              <group
                name="mmt_folia_tree_02005_32"
                position={[-2.38, 0, -9.676]}
                rotation={[-Math.PI, -0.654, -Math.PI]}
                scale={2.096}>
                <mesh
                  name="Object_72"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_72.geometry}
                  material={materials['mct_atlas.002']}
                />
                <mesh
                  name="Object_73"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_73.geometry}
                  material={materials['mmt_foliage.001']}
                />
              </group>
              <group
                name="mmt_folia_tree_02006_33"
                position={[2.601, 0, -4.218]}
                rotation={[0, 0.6, 0]}
                scale={0.666}>
                <mesh
                  name="Object_75"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_75.geometry}
                  material={materials['mct_atlas.002']}
                />
                <mesh
                  name="Object_76"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_76.geometry}
                  material={materials['mmt_foliage.001']}
                />
              </group>
              <group name="Empty001_89" position={[1.998, 0, 0]} rotation={[0, -Math.PI / 2, 0]}>
                <group name="root001_88" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                  <group name="GLTF_created_0">
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                    <skinnedMesh
                      name="Object_82"
                      geometry={nodes.Object_82.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_82.skeleton}
                    />
                    <skinnedMesh
                      name="Object_84"
                      geometry={nodes.Object_84.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_84.skeleton}
                    />
                    <skinnedMesh
                      name="Object_86"
                      geometry={nodes.Object_86.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_86.skeleton}
                    />
                    <skinnedMesh
                      name="Object_88"
                      geometry={nodes.Object_88.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_88.skeleton}
                    />
                    <skinnedMesh
                      name="Object_90"
                      geometry={nodes.Object_90.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_90.skeleton}
                    />
                    <skinnedMesh
                      name="Object_92"
                      geometry={nodes.Object_92.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_92.skeleton}
                    />
                    <skinnedMesh
                      name="Object_94"
                      geometry={nodes.Object_94.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_94.skeleton}
                    />
                    <skinnedMesh
                      name="Object_96"
                      geometry={nodes.Object_96.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_96.skeleton}
                    />
                    <skinnedMesh
                      name="Object_98"
                      geometry={nodes.Object_98.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_98.skeleton}
                    />
                    <skinnedMesh
                      name="Object_100"
                      geometry={nodes.Object_100.geometry}
                      material={materials['mct_atlas.001']}
                      skeleton={nodes.Object_100.skeleton}
                    />
                    <skinnedMesh
                      name="Object_102"
                      geometry={nodes.Object_102.geometry}
                      material={materials['mct_atlas.001']}
                      skeleton={nodes.Object_102.skeleton}
                    />
                    <group name="mct_char_base001_77" />
                    <group name="mmt_armor_s_boot001_78" />
                    <group name="mmt_armor_s_chest001_79" />
                    <group name="mmt_armor_s_elbow001_80" />
                    <group name="mmt_armor_s_glove001_81" />
                    <group name="mmt_armor_s_helm001_82" />
                    <group name="mmt_armor_s_hip001_83" />
                    <group name="mmt_armor_s_knee001_84" />
                    <group name="mmt_armor_s_shoulder001_85" />
                    <group name="mmt_prop_shield_07_86" />
                    <group name="mmt_prop_sword_01_87" />
                  </group>
                </group>
              </group>
              <group
                name="Empty_144"
                position={[-1.993, 0, 0]}
                rotation={[Math.PI / 2, 0, -Math.PI / 2]}
                scale={0.01}>
                <group name="root_143">
                  <group name="GLTF_created_1">
                    <primitive object={nodes.GLTF_created_1_rootJoint} />
                    <skinnedMesh
                      name="Object_150"
                      geometry={nodes.Object_150.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_150.skeleton}
                    />
                    <skinnedMesh
                      name="Object_152"
                      geometry={nodes.Object_152.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_152.skeleton}
                    />
                    <skinnedMesh
                      name="Object_154"
                      geometry={nodes.Object_154.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_154.skeleton}
                    />
                    <skinnedMesh
                      name="Object_156"
                      geometry={nodes.Object_156.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_156.skeleton}
                    />
                    <skinnedMesh
                      name="Object_158"
                      geometry={nodes.Object_158.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_158.skeleton}
                    />
                    <skinnedMesh
                      name="Object_160"
                      geometry={nodes.Object_160.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_160.skeleton}
                    />
                    <skinnedMesh
                      name="Object_162"
                      geometry={nodes.Object_162.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_162.skeleton}
                    />
                    <skinnedMesh
                      name="Object_164"
                      geometry={nodes.Object_164.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_164.skeleton}
                    />
                    <skinnedMesh
                      name="Object_166"
                      geometry={nodes.Object_166.geometry}
                      material={materials.mct_atlas}
                      skeleton={nodes.Object_166.skeleton}
                    />
                    <skinnedMesh
                      name="Object_168"
                      geometry={nodes.Object_168.geometry}
                      material={materials['mct_atlas.001']}
                      skeleton={nodes.Object_168.skeleton}
                    />
                    <skinnedMesh
                      name="Object_170"
                      geometry={nodes.Object_170.geometry}
                      material={materials['mct_atlas.001']}
                      skeleton={nodes.Object_170.skeleton}
                    />
                    <group name="mct_char_base_132" />
                    <group name="mmt_armor_c_boot_133" />
                    <group name="mmt_armor_c_chest_134" />
                    <group name="mmt_armor_c_elbow_135" />
                    <group name="mmt_armor_c_glove_136" />
                    <group name="mmt_armor_c_helm_137" />
                    <group name="mmt_armor_c_hip_138" />
                    <group name="mmt_armor_c_knee_139" />
                    <group name="mmt_armor_c_shoulder_140" />
                    <group name="mmt_prop_axe_03_141" />
                    <group name="mmt_prop_shield_02_142" />
                  </group>
                </group>
              </group>
              <group name="Plane_145" position={[-0.042, 3.149, 0.604]} scale={0.819}>
                <mesh
                  name="Object_214"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_214.geometry}
                  material={materials.mct_atlas}
                />
              </group>
              <group name="Cube002_146" position={[2.19, 3.149, 0.681]}>
                <mesh
                  name="Object_216"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_216.geometry}
                  material={materials.mct_atlas}
                />
              </group>
              <group name="Cube003_147" position={[3.737, 3.149, 0.845]}>
                <mesh
                  name="Object_218"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_218.geometry}
                  material={materials.mct_atlas}
                />
              </group>
              <group
                name="Cube004_148"
                position={[-2.192, 3.149, 0.681]}
                rotation={[0, 0, Math.PI]}>
                <mesh
                  name="Object_220"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_220.geometry}
                  material={materials.mct_atlas}
                />
              </group>
              <group name="Cube005_149" position={[-3.739, 3.149, 0.845]}>
                <mesh
                  name="Object_222"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_222.geometry}
                  material={materials.mct_atlas}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/character_fight.glb')
