/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ahmad Riazi (https://sketchfab.com/ahmadriazi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/balenciaga-hoodie-e37b7c42f1c34e71b76bc42acc2acc4f
Title: Balenciaga Hoodie
*/

import React, { useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { useAtom } from 'jotai';
import { colorAtom } from './UI';

export function Hoodie(props) {

  const { nodes, materials } = useGLTF('/hoodie.glb')

   const [color] = useAtom(colorAtom);

   Object.keys(materials).forEach((key) => {
    if (materials[key].color) {
      materials[key].color.set(new THREE.Color(color));
    }
  });

  return (
    <group {...props} dispose={null}>
      <group scale={0.4}>
        <group  scale={0.01}>
        <group scale={10}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['1_0_Default_FRONT_3061_0'].geometry}
              material={materials['0_Default_FRONT_3061']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['1_0_Default_FRONT_3061_0001'].geometry}
              material={materials['0_Default_FRONT_3061_0']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['1_0_Default_FRONT_3061_0002'].geometry}
              material={materials['0_Default_FRONT_3061_1']}
            />
          </group>
          <group scale={10}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['2_0_Default_FRONT_3061_0'].geometry}
              material={materials['0_Default_FRONT_3061_2']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['2_0_Default_FRONT_3061_0001'].geometry}
              material={materials['0_Default_FRONT_3061_3']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['2_0_Default_FRONT_3061_0002'].geometry}
              material={materials['0_Default_FRONT_3061_4']}
            />
          </group>
          <group scale={10}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['3_0_Default_FRONT_3061_0'].geometry}
              material={materials['0_Default_FRONT_3061_5']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['3_0_Default_FRONT_3061_0001'].geometry}
              material={materials['0_Default_FRONT_3061_6']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['3_0_Default_FRONT_3061_0002'].geometry}
              material={materials['0_Default_FRONT_3061_7']}
            />
          </group>
          <group scale={10}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['4_0_Default_FRONT_3061_0'].geometry}
              material={materials['0_Default_FRONT_3061_17']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['4_0_Default_FRONT_3061_0001'].geometry}
              material={materials['0_Default_FRONT_3061_18']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['4_0_Default_FRONT_3061_0002'].geometry}
              material={materials['0_Default_FRONT_3061_19']}
            />
          </group>
          <group scale={10}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['5_0_Default_FRONT_3061_0'].geometry}
              material={materials['0_Default_FRONT_3061_8']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['5_0_Default_FRONT_3061_0001'].geometry}
              material={materials['0_Default_FRONT_3061_9']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['5_0_Default_FRONT_3061_0002'].geometry}
              material={materials['0_Default_FRONT_3061_10']}
            />
          </group>
          <group scale={10}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['6_0_Default_FRONT_3061_0'].geometry}
              material={materials['0_Default_FRONT_3061_11']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['6_0_Default_FRONT_3061_0002'].geometry}
              material={materials['0_Default_FRONT_3061_13']}
            />
          </group>
          <group scale={10}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['7_0_Default_FRONT_3061_0'].geometry}
              material={materials['0_Default_FRONT_3061_14']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['7_0_Default_FRONT_3061_0001_1'].geometry}
              material={materials['0_Default_FRONT_3061_15']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['7_0_Default_FRONT_3061_0001_2'].geometry}
              material={materials['0_Default_FRONT_3061_12']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['7_0_Default_FRONT_3061_0002'].geometry}
              material={materials['0_Default_FRONT_3061_16']}
            />
          </group>
          <group scale={10}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['8_0_Default_FRONT_3061_0'].geometry}
              material={materials['0_Default_FRONT_3061_20']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['8_0_Default_FRONT_3061_0001'].geometry}
              material={materials['0_Default_FRONT_3061_21']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['8_0_Default_FRONT_3061_0002'].geometry}
              material={materials['0_Default_FRONT_3061_22']}
            />
          </group>
          <group scale={10}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Pattern2D_454051_0_Default_FRONT_3061_0.geometry}
              material={materials['0_Default_FRONT_3061_23']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Pattern2D_454051_0_Default_FRONT_3061_0001.geometry}
              material={materials['0_Default_FRONT_3061_24']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Pattern2D_454051_0_Default_FRONT_3061_0002.geometry}
              material={materials['0_Default_FRONT_3061_25']}
            />
          </group>
          <group scale={10}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Pattern2D_456047_0_Default_FRONT_3061_0.geometry}
              material={materials['0_Default_FRONT_3061_26']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Pattern2D_456047_0_Default_FRONT_3061_0001.geometry}
              material={materials['0_Default_FRONT_3061_27']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Pattern2D_456047_0_Default_FRONT_3061_0002.geometry}
              material={materials['0_Default_FRONT_3061_28']}
            />
          </group>
          <group scale={10}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Pattern2D_603150_0_Default_FRONT_3061_0.geometry}
              material={materials['0_Default_FRONT_3061_29']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Pattern2D_603150_0_Default_FRONT_3061_0001.geometry}
              material={materials['0_Default_FRONT_3061_30']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Pattern2D_603150_0_Default_FRONT_3061_0002.geometry}
              material={materials['0_Default_FRONT_3061_31']}
            />
          </group>
          <group scale={10}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Pattern2D_603151_0_Default_FRONT_3061_0.geometry}
              material={materials['0_Default_FRONT_3061_32']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Pattern2D_603151_0_Default_FRONT_3061_0001.geometry}
              material={materials['0_Default_FRONT_3061_33']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Pattern2D_603151_0_Default_FRONT_3061_0002.geometry}
              material={materials['0_Default_FRONT_3061_34']}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/hoodie.glb')
